- src/ZoneSettings.h
.. cause its really annoying not to have one :)
> Add warning for zonal setting overwrite

- example/runexternal.py
- example/runexternal.xml
- src/Handlers.cpp.Rt
- src/Solver.cpp.Rt
- src/Solver.h.Rt
> revised python support

- src/cross.h
> Fixing d3q19 double/single precision bug

- src/Handlers.cpp.Rt
- src/lib/boundary.R
I added properly working template for symmetry boundary condition. 
First argument is direction of symmetry, second - sign of vector; similarly to ZouHe. 
Example: 
```cuda
CudaDeviceFunction void BottomSymmetry() {
<?R SymmetryNew(2, 1) ?>
}
> Adding proper Symmetry BC

- .github/CONTRIBUTING.md
> Adding rule regarding XXX_new

- src/Handlers.cpp.Rt
- src/d2q9_plate/Dynamics.R
- src/d2q9_plate/Dynamics_adj.c.Rt
Fixed the cut-off of parameters in the optimization procedure.
Added missing adjoint dynamics to d2q9_plate
> Fixing bounds on optimization parameters

- src/config.main.mk.in
- src/configure.ac
To help with #65 . As proposed by @mdzik
>  Adding profiling option to configure

- doc/elements.yaml
- src/Handlers.cpp.Rt
- src/Lattice.cu.Rt
I added the possibility to use COBYLA and Nelder-Mead optimization algorithms that do not need the gradient (no need for adjoint calculation).
> Adding possibility of optimization with gradient free algorithms

- README.md
> I think that should be clearfied

- .github/CONTRIBUTING.md
- example/pythonGeom.xml
- src/Geometry.cpp.Rt
- src/Handlers.cpp.Rt
- src/Solver.cpp.Rt
- src/Solver.h.Rt
- src/utils.h
I added the PythonInline geometry element. Bit experimental*, but with this making "fancy" geometry is much cleaner: no need to outside script.
Performance should be comparable to the rest of the code, function is parsed/compiled once and then executed.
Additional you have state-full  Python environment in whole "< nx= ny=>" box
*) might be unstable, I hope I fixed all thread/gis related issues, but one never knows. Should have no impact on solving part of the solver. Python is finalized after processing geometry block.
> PythonInline geometry element

- doc/elements.yaml
- src/Handlers.cpp.Rt
- src/ZoneSettings.h
- src/spline.h
- src/unit.cpp
- src/unit.h
I added support for B-Spline parametrisation/smoothing for optimal control problems. You can selected with
```xml
<BSpline nodes="10" lower="-1" upper="1">
<OptimalControl what="Velocity-inlet"/>
</BSpline>
```
> B-Spline parametrisation for optimal control

- src/Global.cpp.Rt
- src/Global.h.Rt
- src/Solver.cpp.Rt
- src/main.cpp.Rt
- tools/csvdiff
- tools/tests.sh
I added a "Walltime" column to the csv log, with the wall clock time from the beginning of execution.
> Adding wall clock time to Log

- src/Handlers.cpp.Rt
one-line-too-long comment
I fixed #88
> too much commented, fixes #88

- doc/elements.yaml
- src/Handlers.cpp.Rt
Adding element for repeated (periodic) optimal control. Sometime it is needed (normally the control is repeated, but sometimes we need different periods for different controls.
> Adding RepeatControl

- src/Handlers.cpp.Rt
- src/Sampler.cpp.Rt
- src/Sampler.h
I fixed some issues with output format of Sampler. Now it should be in a better form and suitable for analysis.
> Fix of Sampler output

- src/Handlers.cpp.Rt
- src/d2q9_plate/Dynamics.R
- src/d2q9_plate/Dynamics.c.Rt
I added the some additional options for parametrization of optimal control, such as flipping periodic repetition of specified waveform.
I added smoothing parameter to the immerse boundary implementation in d2q9_plate
> Smooth immerse boundary in d2q9_plate and further optimal control parametrisation options

- src/d2q9_plate/Dynamics.R
- src/d2q9_plate/Dynamics.c.Rt
- src/vtkLattice.cpp.Rt
I added offset to immerse boundary in d2q9_plate
And corrected the lack of comma in TXT output
> Adding offset to immerse boundary in d2q9_plate

- tools/dep.R
Fixed tools/dep.R, which was not working for multiple paths (Handlers/...)
> [V6.1 RC] Fixed dependency generator

- src/Handlers/cbPythonCall.cpp
- src/Solver.cpp.Rt
- src/Solver.h.Rt
> Adding spelling fix to v6.1

- src/makefile.main.Rt
Minor cleanup in the makefile related to creation of paths.
> Fixed path creation in makefile

- .travis.yml
- src/makefile.main.Rt
Moved the installation of CUDA on Travis-CI to "apt" addon to go around #144
> Change CUDA installation on Travis-CI

- models/moving/d2q9_plate/Dynamics.R
- src/Handlers/acObjective.cpp.Rt
- src/Handlers/acObjective.h
- src/Handlers/cbRunR.cpp.Rt
- src/conf.R
Added "Objectives" list to the conf.R, and related AddObjective function.
Added an objective "EfficiencyX" and "-Y" to d2q9_plate
Added support for setting zone settings with RunR
> Adding support for defining non-linear objectives for optimization

- src/config.mk.in
- src/configure.ac
- src/makefile.Rt
- tools/install.sh
Modified configure and makefiles to support CC and CXX variables to enable compilation with different compilers (like cray or intel)
> Configuration on different compilers

- .travis.yml
- models/flow/d2q9/Description.md
- models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
- src/conf.R
- src/makefile.main.Rt
- src/models.R
- tools/deploy.docs.sh
- tools/gen.doc.R
- tools/install.sh
- tools/stensil.plot.R
Adding docs auto-generation as a additional step in Travis-CI. Works for branches of CFD-GO/TCLB, and deploys to: https://branch--tclb.netlify.com/
> [V6.2 RC] Adding docs auto-generation to Travis-CI

- doc/elements.yaml
- src/Handlers/cbPID.cpp.Rt
- src/Handlers/cbPID.h
I added a handler for control of a specified Global variable with the change of a specified (zonal) setting.
example:
```
<PID Flux="10.0" control="ForceX" scale="0.01" DerivativeTime="100" IntegrationTime="10000" Iterations="10"/>
```
Can be used with units:
```
<PID Flux="10m3/s" control="ForceX" scale="0.01Ns/m3" DerivativeTime="100s" IntegrationTime="100s" Iterations="10"/>
```
> Adding PID controller Handler

- src/Handlers/acAndersen.cpp
- src/Handlers/acAndersen.h
- src/Lattice.cu.Rt
- src/Lattice.h.Rt
I added a handler for Andersen steady-state solver. It is a Krylov-space like approach for improving the convergence of fixed-point iterations. Usage:
```xml
<Andersen Directions="10" Eps="1e-6" Times="30">
<Solve Iterations="1000"/>
</Andersen>
```
The algorithm is executed separately on all processes (not a bad thing, but it would be nice to make it an option in the future).
> [V6.2 RC] Andersen Handler

- example/runr/spheres.xml
- src/Handlers/cbRunR.cpp.Rt
- tools/install.sh
Added X,Y and Z components to Solver$Geometry to help with calculating geometrical things. Also added an example.
> [V6.2 RC] [RunR] Adding X,Y and Z to Geometry in RunR

- models/multiphase/d2q9_pf_velocity/Description.md
- models/multiphase/d2q9_pf_velocity/Dynamics.R
- models/multiphase/d2q9_pf_velocity/Dynamics.c.Rt
- models/multiphase/d2q9_pf_velocity/conf.mk
- models/multiphase/d3q27_pf_velocity/Description.md
- models/multiphase/d3q27_pf_velocity/Dynamics.R
- models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
- models/multiphase/d3q27_pf_velocity/conf.mk
I modified the model d2q9_pf_velocity and d3q27_pf_velocity
Added inflow and outflow boundary conditions to these models as well as descriptions for incorporation in the website.
> [V6.2 RC] new BC for phase field models

- README.md
- tools/install.sh
I updated the install.sh to make it working with CentOS.
I tested the script on VM with:
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core) 
Release:        7.4.1708
Codename:       Core
Unfortunately, I don't have GPU to test, thus cuda part is missing from the script.
> CentOS install script

- models/moving/d2q9_plate/Dynamics.R
- models/moving/d2q9_plate/Dynamics.c.Rt
I added units to d2q9_plate model
> Fixed units in d2q9_plate

- example/flow/2d/d2q9_SRT_example.xml
- models/flow/d2q9_SRT/Dynamics.c
- models/multiphase/d2q9_pf_velocity/Dynamics.R
- models/multiphase/d2q9_pf_velocity/Dynamics.c.Rt
- models/multiphase/d3q27_pf_velocity/Dynamics.R
- models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
Only small adjustments, but so there is not any large divergence.
I modified the model:
- d2q9_SRT: student couldn't run d2q9_srt_example.xml, adjustments so that this now runs okay.
- d2q9_pf_velocity: play with convective outlet
- d3q27_pf_velocity: 
- Added smoothing section for assisting initialisation from recommendation of gg
- Convective and velocity boundaries
- Three phase contact
- Some initialisation geometries that I really need to write into geometry rather than here.
> Minor additions to TM phase field models

- src/Handlers/cbPythonCall.cpp
Added
<?CallPython pythonpath="XXXXXXX" option
> Introduce python path update from XML level

- src/configure.ac
> Numpy path is distro-dependent. Autodetection needed and already build-in numpy

- src/LatticeContainer.inc.cpp.Rt
> Fix debug build in gcc 7 

- models/heat/d3q27_tePSM_per/Dynamics.R
- models/heat/d3q27_tePSM_per/Dynamics.c.Rt
- models/heat/d3q27_tePSM_per/conf.mk
…J. McCullough
I added:
- the model: d3q27_tePSM_per a total energy thermal model based on the work of Guo et al. PRE 75,036704 (2007)
> 3D thermal model development

- src/Makefile.in.Rt
- src/configure.ac
I enabled the `--with-cuda-arch=sm_60` flag in configure.
Now its working on nVidia Pascal architecture.
Tested on Quadro P620.
> adding sm_60

- .github/CONTRIBUTING.md
Fixed issue #205 - CONTRIBUTING.md general grammar and spelling mistakes.
> Fixes spelling & grammar in CONTRIBUTING.md

- .github/CONTRIBUTING.md
- src/makefile.main.Rt
> Hotfix #210 to upstream

- tools/install.sh
- tools/tests.sh
I fixed Rdep installation in evn with proxy
> I fixed Rdep installation in evn with proxy

- .gitignore
- tools/tests.sh
I added the mode to torture yourself repeatedly :]
> Feature: repeated tests run

- src/CommonHandler.h
- src/Handlers/acRemoteForceInterface.cpp
- src/def.cpp.Rt
- src/pugiconfig.hpp
- src/pugixml.cpp
- src/pugixml.hpp
We've been using 7yo pugi... It's supposed to be faster ;)
> upgrade pugixml version

- src/configure.ac
This becomes usefull in some environments, I've made it long ago and i'm quite uncertaing if it's still needed.
> Feature obey system $compilerbindir

- doc/elements.yaml
- tools/gen.doc.R
Corrected an error in the gen.doc script.
> Correcting xml documentation generation

- .travis.yml
- src/Geometry.cpp.Rt
- src/Handlers/acOptSolve.cpp
- src/Handlers/acSAdjoint.cpp
- src/Handlers/acSolve.cpp
- src/Handlers/acUSAdjoint.cpp
- src/cross.h
Corrected the depreciated CudaThreadSynchronize and moved the Travis-CI tests to `sm_30`. (this PR separates this issue from #230 )
> Updates for moving to sm_30

- README.md
@corneels I hope you don't mind we'll take your text corrections.
> Fixed some minor syntax in readme

- src/Handlers/cbFailcheck.cpp.Rt
Solves issue reported by @ggruszczynski
> Fixing memory leak in Failcheck

- example/heat/d3q27q27_Hot_Karman_Re100_Pr5.xml
- models/heat/d3q27q27_cm_cht/Dynamics.R
- models/heat/d3q27q27_cm_cht/Dynamics.c.Rt
- models/heat/d3q27q27_cm_cht/conf.mk
- src/Geometry.cpp.Rt
Cleanup and various improvements to the d3q27q27_cm_cht model
- added an example
- added averaging option
- fixed stl reading issues
- CHT becomes a compilation option
> D3q27q27 cm cht goes2cfdgo

- src/Handlers/cbStop.cpp.Rt
- src/Handlers/cbStop.h
Adding possibility of stopping on limit to `<Stop />` element.
`<Stop Iterations="10" FluxAbove="0.1"\>`
To stop if `Flux` is above `0.1` (the check will be made every `10` iterations).
`<Stop Iterations="10" FluxBelow="0.1"\>`
To stop if `Flux` is below `0.1`.
`<Stop Iterations="10" FluxBelow="0.2" FluxAbove="0.1" Times="10"\>`
To stop if `Flux` is between `0.1` and `0.2`, `10` times in a row.
FYI: @TravisMitchell
> Adding stop on limit

- example/multiphase/d2q9_pf_velocity/Droplet_Falling_2D.xml
- models/multiphase/d2q9_pf_velocity/Dynamics.R
- models/multiphase/d2q9_pf_velocity/Dynamics.c.Rt
- models/multiphase/d2q9_pf_velocity/conf.mk
+ General tidy up of the model and addition of options feature to allow for various collision operators without any extra code compilation. 
+ Added fixedIterator, needs to be greater than 1 for dynamic cases particularly if continuous phase is gas
+ Double checked grad and laplace operators and chemical potential calculations
+ Added droplet falling example that was where issues were noted.
> + Issue with d2q9_pf_velocity clean up and fix + example

- tools/compareH5.py
Added a python script for testing - takes argument of two file names and additional optional argument for tolerance. Then steps through all fields in the two files and compares for any difference.
> + addition of file to compare 2 h5 output files

- src/Geometry.cpp.Rt
- src/Handlers/cbPythonCall.cpp
- src/Lattice.cu.Rt
- src/LatticeAccess.inc.cpp.Rt
- src/LatticeContainer.inc.cpp.Rt
- src/Region.h
- src/RemoteForceInterface.h
- src/Sampler.cpp.Rt
- src/Sampler.h
- src/Solver.cpp.Rt
- src/cross.h
- src/gpu_anim.h
- src/vtkOutput.cpp
A cosmetic correction to the include statements
> Correcting the include statements for libraries

- example/heat/d2q9q9_Hot_Karman_Re100_Pr5.xml
- models/heat/d2q9q9_cm_cht/Description.md
- models/heat/d2q9q9_cm_cht/Dynamics.R
- models/heat/d2q9q9_cm_cht/Dynamics.c.Rt
- models/heat/d2q9q9_cm_cht/conf.mk
- models/heat/d3q27q27_cm_cht/Dynamics.c.Rt
Added 2d cht model.
Improved VTK output in 3d cht model.
> added 2d cm cht model

- .travis.yml
- doc/elements.yaml
- src/Handlers/acContainer.cpp
- src/Handlers/acContainer.h
- src/Handlers/acRunAction.cpp.Rt
- src/Handlers/acRunAction.h
- src/Lattice.cu.Rt
- src/Lattice.h.Rt
- src/conf.R
- src/schema.xsd.Rt
There was not interface for running other actions then Init and Iteration
Added `<RunAction/>` element for running specific action by name:
```xml
<Container> 
<Stop L2ChangeNormBelow="1e-4" Times="10"/> 
<RunAction name="TempUpdate" Iterations="1000000"/> 
</Container>
```
fixes #278 
@TravisMitchell Can you test if it fits the application you had in mind?
> Adding RunAction

- src/Geometry.cpp.Rt
- src/Handlers/cbPythonCall.cpp
- src/configure.ac
I've added python3 support + added support for recent 3.8 python-config changes
https://docs.python.org/dev/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build
Mergeable if tests will pass
> Python 2.X is out-of-life.

- models/multiphase/d2q9_ShanChen/Dynamics.R
- models/multiphase/d2q9_ShanChen/Dynamics.c.Rt
Simple ZH type BC for flat moving boundary
> Moving wall BC for ShanChen model

- example/moving/flapping1.xml
> Fix relativepath in example

- example/nonnewtonian/kl_cyl_test.xml
- models/nonnewtonian/d3q27_kl/Dynamics.R
- models/nonnewtonian/d3q27_kl/Dynamics.c.Rt
- models/nonnewtonian/d3q27_kl/conf.mk
Added the model d3q27_kl model, which is based off the non-Newtonian Kuang-Luo rheology.
- OutFlow option adds Zero-Gradient/Neumann boundaries
> d3q27_kl model

- src/conf.R
This PR introduces a test for the unit argument in `Dynamics.R` calls no to be an empty string.
Closes #312
> Test for empty unit

- .github/workflows/test.yml
- .travis.yml
- src/Handlers/OptimalControl.cpp.Rt
- src/Handlers/OptimalControlSecond.cpp.Rt
- src/Handlers/acAndersen.cpp
- src/Handlers/acFDTest.cpp
- tools/env.sh
- tools/install.sh
There is a growing problem with testing of installation, compilation and execution of TCLB on the broad range of architectures it runs on.
The first steps include:
- support for installation of all dependencies (as automatic as possible) on different platforms
- ability to compile on different platforms (including code generation and all scripts)
- GitHub Action which will test the code (installation, compilation and execution), which will as platform independent as possible.
This PR virtually rewrites the `tools/install.sh` to cope better with command-line options. The new version of the script will install essential tools (needed on macos), R, openmpi, and R  packages, on `apt`, `yum` and `brew` based systems.
Additionally this PR adds a GitHub workflow, which calls the …
> Install.sh rewrite, GitHub Actions support and MacOS support

- src/Solver.cpp.Rt
- src/ZoneSettings.h
- src/conf.R
> Correcting for edge cases

- tools/dep.R
This PR corrects an error in the regexp in `tools/dep.R`
> Correcting error in tools/dep.R

- src/config.mk.in
- src/configure.ac
> Fixing issue with mpi compilation options discovery

- README.md
- tools/install.sh
README update and help for `install.sh`
@ndivaira I would ask you to check the english in the whole README and suggest changes in the review to this pull request. You can see the new README as a single file here: https://github.com/llaniewski/TCLB/blob/fix/readme/README.md
> Update to readme

- .travis.yml
- tools/install.sh
> Fixing errors in rpackages installation

- src/ADTools.cu
- src/ADpost.sed.Rt
- src/ADpre_b.h.Rt
- src/makefile.main.Rt
- tools/ADmod.R
- tools/makeAD
The bug was introduced in #258 commit:
https://github.com/CFD-GO/TCLB/commit/1ccec01dd0e0f2a0daa69edbb646e3a352d6645a#diff-fba2476a71a879cd35e9598523ecc3c520dc84a28cfc30ad57bdfaefbac6e844
@mrutkowski-aero This fixes the adjoint compilation. I will merge it when tests finish.
> Correcting bug for adjoint compilation in makefile

- src/utils.h
> Adding checks on existance in read of gzip files

- doc/elements.yaml
- example/flow/2d/karman_checkpointExample.xml
- src/Handlers/cbSaveCheckpoint.cpp
- src/Handlers/cbSaveCheckpoint.h
- src/Lattice.cu.Rt
- src/Lattice.h.Rt
- src/Solver.cpp.Rt
- src/Solver.h.Rt
I added checkpoint feature to improve the usability of this function. User specifies how many checkpoints to keep saved, the default is one. A restart xml file is created that has a loadBinary element added prior to the first solve element.
> Feature checkpoint

- example/multiphase/d2q9_pf_velocity/cm_dam_break.xml
- example/multiphase/d2q9_pf_velocity/mrt_dam_break.xml
- example/multiphase/d3q27_pf_velocity/ContactAngle_45.xml
- example/multiphase/d3q27_pf_velocity/ContactAngle_45_symX.xml
- example/multiphase/d3q27_pf_velocity/ContactAngle_45_symXZ.xml
- example/multiphase/d3q27_pf_velocity/annularTaylorBubble_DasC.xml
- models/multiphase/d2q9_pf_velocity/Dynamics.R
- models/multiphase/d2q9_pf_velocity/Dynamics.c.Rt
- models/multiphase/d3q27_pf_velocity/Dynamics.R
- models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
- models/multiphase/d3q27_pf_velocity/conf.mk
- src/Handlers/cbRunR.cpp.Rt
I removed duplicate variables from pf_velocity models and updated the examples.
I added velocity boundary condition to d3q27_pf_velocity model.
I added export of densities for machine learning (ML) as an option in d3q27_pf_velocity.
I added double square bracket rinside capability.
> Pf velocity devs

- src/configure.ac
> Add support for CUDA Compute Capability 8.0

- src/simplepart.cpp
Adding options to force averaging to simplepart (off by default). To use:
```xml
<Log name="out.csv" Iterations="64" average="y"/>
```
FYI @TravisMitchell
> Adding force averaging to simplepart

- src/configure.ac
Used for instance for NVIDIA V100 on Topaz
> Add cuda compute 7.0

- src/Geometry.cpp.Rt
- src/Handlers/cbPythonCall.cpp
> Fixing depreciated python API

- example/particle/3d/channel-particles.xml
- example/particle/3d/in.channel-particles
Added files to example for the particle tutorial that nathan wrote to allow users to error check if something goes wrong.
> Add solution files to Nathan's particle tutorial

- example/multiphase/d3q27_pf_velocity/ContactAngle_45.xml
- example/multiphase/d3q27_pf_velocity/RayleighTaylorInstability_3D.xml
I removed reference to a zone that is no longer created in an example file and increased run time of RayleighTaylor so that it does more interesting things
> Very minor change to fix an example file so that it runs

- README.md
Added link to guide for installing CUDA inside WSL.
> Add link for CUDA on WSL in readme

- src/unit.cpp
- src/unit.h
Units can have fractional powers (eg. "1m/s1.3")
> Unit powers can be fractional

- .codecov.yaml
- .github/actions/install/action.yaml
- .github/workflows/cpu_test.yml
- .github/workflows/gpu_comp.yml
- README.md
- src/configure.ac
- src/lib/feq.R
- tools/install.sh
This PR:
- updates the contributor list and corrects the `README.md`
- removes `numbers` package from dependencies, as several users had problem with it (and it was used only for GCD)
- makes codecov not fail on reduced coverage
> Update of minor things

- src/LatticeAccess.inc.cpp.Rt
- src/cross.cu
> Fixing dynamic access in 2D

- src/Handlers/cbRunR.cpp
Develop doesn't currently compile with rinside. Needs simple fix for grabbing c string.
> + fix compile to grab c string from cpp string

- src/Handlers/acFDTest.cpp
- src/Handlers/cbSaveMemoryDump.cpp
- src/Handlers/cbVTK.cpp
- src/Lattice.cpp.Rt
- src/cross.cu
- src/main.cpp
- Cartesian lattice-specific functionality has been moved from `Solver` to `Lattice`
- `LatticeBase` introduced as base class for common Cartesian and arbitrary functionality
- Handlers using `solver->lattice` now use a dynamic cast
- Various utility tweaks related to the introduction of C++ 17
> Refactor in preparation for arbitrary grid

- src/Handlers/cbRunR.cpp
Fixes #463 . Tested on the example that was failing previously, now is working.
> Fix RunR geometry 

- .gitignore
- tools/overlay.sh
> nicely formatted gitignore

- models/particles/d3q27_PSM/Dynamics.R
- models/particles/d3q27_PSM/Dynamics.c.Rt
- models/particles/d3q27_PSM/conf.mk
Multisphere model from @ndivaira
> Support for overlapping spheres for the `d3q27_PSM` model

- src/LatticeAccess.inc.cpp.Rt
@bhill23 This should fix the compilation issue for the `master` branch
> Fixing NodeType fetching in autosym

- src/ArbConnectivity.hpp
- src/ArbLattice.cpp
- src/ArbLattice.hpp
- src/CartLattice.cpp.Rt
- src/Handlers/Action.cpp
- src/Handlers/cbFailcheck.cpp
- src/PartitionArbLattice.cpp
- src/PartitionArbLattice.hpp
- src/Solver.cpp
- src/UtilTypes.hpp
- src/pinned_allocator.hpp
- src/utils.cpp
- src/utils.h
- src/vtuOutput.cpp
This removes a lot of standard library things that are not commonly supported.
> Removing C++17 standard library stuff

- src/Sampler.cpp
You are right, I changed *tmp to tmp[3] now
> Fixed Sample handler for vector_t quantities
