- src/Handlers.cpp.Rt
I implemented, what was proposed in issue #49 . Now post-Failcheck action can be performed, such as basic VTK or even something like this:
```xml
<Failcheck Iterations="1000">
<Solve Iterations="2000">
<VTK name="withnan" Iterations="500"/>
</Solve>
</Failcheck>
```
> Execution after NaN

- .github/CONTRIBUTING.md
- src/Geometry.cpp.Rt
- src/Geometry.h
- src/Handlers.cpp.Rt
- src/d3q19_heat/Dynamics.R
- src/lib/boundary.R
I added the feature in the Geometry module, that allows to specify if a node should be:
- `mode="overwrite"` -- Overwrites the previous value of the node type
- `mode="change"` -- Overwrites only non-zero node types.
- `mode="fill"` -- Sets the node type only in elements that didn't have the node type earlier (had 0 in this `mask`)
Example:
```xml
<EVelocity mode="fill">
```
will set the EVelocity boundary condition only on elements that don't have previously set boundary condition.
@mdzik @shkodm
> Adding support for "drawing" mode in Geometry

- src/Handlers.cpp.Rt
- src/Lattice.cu.Rt
- src/Lattice.h.Rt
- src/ZoneSettings.cpp
- src/ZoneSettings.h
- src/config.mk.in
Adding:
1. testing of Adjoint gradient against Finite Difference:
```xml
<FDTest order="2">
<Adjoint>
<Solve Iterations="100"/>
</Adjoint>
</FDTest>
```
2. GenericOptimizer handler class, for all handlers evaluating solutions for changed parameters (in future Threshold handler will be also reimplemented as GenericOptimizer)
3. mechanism for skipping adjoint when gradient is not needed (for instance when Optimize uses a non-gradient algorithm.
4. dumping of time dependent settings to a csv file (a simple dump, more for debugging purposes): `<DumpSettings\>`
> Finite Difference test

- models/flow/d2q9/Dynamics.R
- models/multiphase/d2q9_pf/Dynamics.R
- src/Lattice.cu.Rt
- src/Solver.cpp.Rt
- src/vtkLattice.cpp.Rt
Corrected the Get_ Set_ and Clear_ functions in Lattice.cu, to work **only** with densities marked as `parameter`. This changes the behaviour of PythonCall, as it can now read and write only such densities/fields. You can declare such density as:
```R
AddDensity(name="G", parameter=TRUE)
```
A density which is marked as parameter can only have streaming direction 0 (dx=0,dy=0,dz=0).
> [V6.1 RC] Corrected the Get_ Set_ functions

- tools/install.sh
Adding full-github option to `tools/install.sh rdep` for people living on the edge.
> [V6.1 RC] Adding full-github option to tools/install.sh

- models/flow/d3q27/Dynamics.c.Rt
- models/flow/d3q27_cumulant/Dynamics.c.Rt
- src/Handlers/acSyntheticTurbulence.cpp
- src/Lattice.cu.Rt
- src/Lattice.h.Rt
- src/LatticeContainer.h.Rt
- src/cuda.cu.Rt
In the view of work with Paweł Obrępalski (@PabloOb ?), I decided that it is better to make the synthetic turbulence as a constant moving random field, and not exponentially convoluted in time as it was earlier.
I modified the procedures accordingly. I will test the spectra soon.
> Modifying the SyntheticTurbulence mechanism

- src/main.cpp.Rt
Added device initialization to that all driver issues would occur in main, and not in first CUDA call.
> Adding device initialization in main (small fix)

- src/Handlers/vHandler.h
Fix for the issue on cray with the division of int and double returning <1 when should be equal to 1. Was causing jobs to continue running past the designated <Solve Iterations=XXX /> for certain cases.
> Fix of iteration count for Cray (int/double division issue)

- src/LatticeAccess.inc.cpp.Rt
- src/LatticeContainer.h.Rt
- src/cuda.cu.Rt
For a given field `A` you can access the neighbours with eg. `A(-1,1)`. But the arguments have to be constant. This means that you cannot *loop over your neighbours*. I added dynamic accessors `A_dyn(dx,dy)`, which can be used with variables. Now you can do:
```c++
real_t sum=0;
for (int dx = -1; dx<=1; dx++) {
for (int dy = -1; dy<=1; dy++) {
sum += A_dyn(dx,dy);
}
}
```
The function returns NAN if the field is accessed outside of it's accessible neighbourhood.
> Adding dynamics access to Fields

- src/conf.R
I (Lukasz really) fixed bug when creating densities via  AddDensity(name="f[X]",...) when X>10.
> + adding bug fix to create more than 10 densities

- src/LatticeContainer.inc.cpp.Rt
- src/conf.R
Corrected the division between Interior and Border elements, for access directions with dy/dz values higher then 1
Fixed a bug, which was causing wrong access conditions if the dx/dy/dz were all eigther positive or negative, and had a spread. E.g. `minx=-2` and `maxx=-1`
> Fixing bug related to wide access (accessing data in wider regions)

- models/experimental/d2q9_inc/Dynamics.R
- models/flow/d2q9/Dynamics.R
- models/flow/d2q9_les/Dynamics.R
- models/flow/d2q9_thin_film/Dynamics.R
- models/multiphase/d2q9_pf/Dynamics.R
- models/optimization/d2q9_adj/Dynamics.R
- models/optimization/d3q19_adj/Dynamics.R
- src/Consts.h.Rt
- src/LatticeAccess.inc.cpp.Rt
- src/conf.R
- src/cuda.cu.Rt
- src/def.cpp.Rt
- src/types.h.Rt
- src/vtkOutput.h
If there is too many NodeTypes, `conf.R` will use `unsigned int` instead of `unsigned short int`.
- Moved Inlet and Outlet node types to the relevant models
- Moved X,Y,Z by 0.5 (to the center of the cell) for a more natural syntax.
> [V6.2 RC] Extend flag_t

- example/multiphase/csf/ContactAngle_45.xml
- example/multiphase/csf/ContactAngle_45_symX.xml
- example/multiphase/csf/ContactAngle_45_symXZ.xml
- models/experimental/d2q9_inc/Dynamics.R
- models/flow/d2q9/Dynamics.R
- models/flow/d2q9_les/Dynamics.R
- models/flow/d2q9_thin_film/Dynamics.R
- models/multiphase/d2q9_pf/Dynamics.R
- models/multiphase/d3q27_pf_velocity/Dynamics.R
- models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
- models/multiphase/d3q27_pf_velocity/conf.mk
- models/optimization/d2q9_adj/Dynamics.R
- models/optimization/d3q19_adj/Dynamics.R
- src/Consts.h.Rt
- src/LatticeAccess.inc.cpp.Rt
- src/conf.R
- src/cuda.cu.Rt
- src/def.cpp.Rt
- src/types.h.Rt
- src/vtkOutput.h
I have implemented three-phase contact interactions to the d3q27_pf_velocity model (variable contact angle). Also used to test autosymmetries in v6.2 as per the three examples added. The BGK option for collision type in this model has also been moved to an option and the MRT collision kernel written by Lucas has been used.
> Update of d3q27_pf_velocity for three-phase contact

- src/LatticeAccess.inc.cpp.Rt
- src/LatticeContainer.h.Rt
- src/conf.R
For fields that are accessed in more then 27 places, LatticeAccess will switch to fully dynamic access of the fields, cutting on the number of template specializations and the final kernel size.
> [V6.2 RC] Switching to dynamic strategy for load of Fields with big stencil

- src/Handlers/MainContainer.cpp
- src/Handlers/cbDumpSettings.cpp
- src/Handlers/cbLog.cpp
- src/Handlers/cbSample.cpp
- src/Handlers/cbSaveBinary.cpp
- src/Handlers/cbSaveMemoryDump.cpp
- src/Lattice.cu.Rt
- src/Solver.cpp.Rt
fix note: ‘__builtin___sprintf_chk’ output between X and X bytes into…a destination of size 1024 warnings in gcc7
```
The -Wformat-overflow=level option detects certain and likely buffer overflow in calls to the sprintf family of formatted output functions. Although the option is enabled even without optimization it works best with -O2 and higher.
For example, in the following snippet the call to sprintf is diagnosed because even though its output has been constrained using the modulo operation it could result in as many as three bytes if mday were negative. The solution is to either allocate a larger buffer or make sure the argument is not negative, for example by changing mday's type to unsigned or by making the type of the second operand of the modulo expression unsigned: 100U.
void* f …
```
> gcc 7 compilation errors

- src/Handlers/GenericAction.cpp
Return value of the handler must be handled somehow.
> Stop XML execution if error occurred (non-zero handler exit status)

- src/Handlers/GenericOptimizer.cpp
- src/Handlers/acOptimize.cpp.Rt
Fixing call to OptimizerInit, which was done only on `mpi.rank == 0` (which caused infinite wait).
> Fixing optimizer start for parallel

- src/Handlers/acObjective.cpp.Rt
- tools/ADmod.R
The bug was causing the ADmod script to skip first line in all functions (this bug should have not affected previous adjoint builds, as it caused compilation error.
> Fixed bug in ADmod.R

- tools/install.sh
`tools/install.sh` was discovering the package manager even when it didn't need it. I moved it into a function, which is called only when needed.
> Requesting package manager only when needed in tools/install.sh

- src/makefile.main.Rt
Fixes #209 
R profiling doens't work right on the Ubuntu for Windows, which causes compilation to crush. The profiling can be still activated by giving `./configure` a relevant option, but it's now not ON by default.
> Correcting unnececary profiling of RT in makefile

- doc/elements.yaml
- src/Geometry.cpp.Rt
Adding support for changing the axis along with the rays are shot to import STL in the `in`/`out` mode.
This will fill elements with `Wall` boundary condition outside of a STL:
```xml
<Wall mask="ALL">
<STL file="file.stl" side="out" ray_axis="x"/>
</Wall>
```
but by selecting the x `ray_axis`, the elements will be marked for filling starting from x=0, and in the direction of growing x. This makes difference **if stl file is not closed** or is aligned a way it would make it hard to cast rays along other axis.
> Adding the ray_axis selection to STL import

- src/Geometry.cpp.Rt
The STL import wasn't working right when a ray happened to be exactly on the edge.
I added a resolution procedure, in which if a point is exactly on the edge, we calculate if it would move in or out of a triangle if a specific (constant) random displacement would be added. This way a point, which will be exactly on the edge of two neighboring triangles will be assigned only to one of them.
> Fixing STL import in edge conditions

- example/particle/2d/chain.xml
- src/Handlers/acESYSParticle.cpp
- src/Handlers/acESYSParticle.h
- src/Handlers/acRemoteForceInterface.cpp
- src/Handlers/acRemoteForceInterface.h
- src/MPMD.hpp
This resolves #223 
After this change one needs to use `<ESYSParticle>` element in stead of the old `<RemoteForceInterface>` element. Now the `<RemoteForceInterface>` is the element **only activating** the RFI mechanics, and can be used with other codes.
> Change of naming of the ESYS-Particle integration element

- src/main.cpp.Rt
In the current version the destructor of Solver is called after `MPI_Finilize`, can cause problems if the destructur (of Solver, Lattice, etc.) is performing MPI calls.
Changed the `solver` object in `main(...)` to a pointer, which is deleted before the `MPI_Finilize`.
> Change to solver as a pointer for cleanup before MPI_Finilize

- doc/elements.yaml
- src/Handlers/cbHDF5.cpp
- src/Handlers/cbHDF5.h
- src/Solver.h.Rt
- src/config.h.in
- src/config.mk.in
- src/configure.ac
- src/glue.hpp
- src/hdf5Lattice.cpp.Rt
- src/hdf5Lattice.h
- src/makefile.main.Rt
I added support for writing [HDF5](https://www.hdfgroup.org/solutions/hdf5/) files, and descriptive [Xdmf](http://www.xdmf.org/index.php/Main_Page) (.xmf) files.
The HDF5 is an established standard for heavy data, with an efficient library for parallel file writing.
The Xdmf is a XML format for describing data stored in HDF5 file that most visualization software can read.
> HDF5 / Xdmf support

- src/config.mk.in
- src/main.cpp
- src/makefile.main.Rt
- src/xpath_modification.cpp
- src/xpath_modification.h
I added support for adding small (and big) modifications to the xml which is being run on the command line.
The syntax quite simple. For instance if you want to set the `output` attribute of your case, that would be:
```bash
CLB/d2q9/main file.xml @output = "test/"
```
Where `@output` can be any [XPath](https://en.wikipedia.org/wiki/XPath) expression matching some attributes. For instance:
```bash
CLB/d2q9/main file.xml //@output = "test/"
```
Would substitute `output` attribute with `test/` *everywhere* in the case file. With this you can do:
```bash
CLB/d2q9/main file.xml //@Viscosity = "0.16"
```
To run your case with a different Viscosity
**The xml file (with all modification) is saved in the output directory with all the results for later inspection**
I implemented three operators: …
> XPath based modification

- src/main.cpp
- src/makefile.main.Rt
- src/mpitools.hpp
To select the GPU, the code assumes that:
- the MPI ranks are distributive in consecutive chunks
- all nodes have the same number of GPUs
And calculates the GPU id as `dev = rank % count`. This doesn't work if any of the assumptions fail.
Now the main function will split the MPI comm on the name of the node, and uses the local rank (the rank with respect to the node) as the device number.
This change doesn't affect the device selection if the assumptions were fulfilled. But will fail if one over-subscribes GPUs (see below)
The code will fail with an error if multiple ranks will select the same gpu (this is called oversubscription). If you want to oversubscribe, add `oversubscribe_gpu="true"` to the `<CLBConfig/>`.
> Correcting the device selection

- src/Global.cpp.Rt
- src/Global.h.Rt
- src/cross.h
- src/glue.hpp
- src/gpu_anim.h
- src/main.cpp
Fixed:
- an error in treatment of `<Param/>` elements without `name` attribute in `<Units/>`. The problem relates to new syntax introduced in #241 
- the wrong order of `<Param/>` elements generated from attributes. The problem relates to new syntax introduced in #241 
- the lack of device reset, which affects sometimes the profiling done with `nvprof`
> Fixing bug in Units

- src/Handlers/cbHDF5.cpp
- src/MPMD.hpp
MPI_Attr_get is superseded by MPI_Comm_get_attr.
http://www.mpich.org/static//docs/v3.0.x/www3/MPI_Attr_get.html
https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node34.htm
For those who care about warnings:
```
[prometheus][plgmuaddieb@login01 GG_TCLB]$ p/make d2q9
Running make on 12 cores
salloc: Pending job allocation 17101469
salloc: job 17101469 queued and waiting for resources
salloc: job 17101469 has been allocated resources
salloc: Granted job allocation 17101469
salloc: Waiting for resource configuration
salloc: Nodes p0701 are ready for job
module purge... OK
module load plgrid/apps/r/3.4.4... OK
module load plgrid/apps/cuda... OK
module load plgrid/apps/r/3.4.4... OK
module load plgrid/tools/openmpi/3.0.0-gcc-4.9.2... OK
module load plgrid/apps/cuda/9.0... OK …
```
> MPI_Attr_get is superseded by MPI_Comm_get_attr

- .codecov.yaml
- .travis.yml
- README.md
- src/conf.R
- src/configure.ac
- src/makefile.main.Rt
- tools/cp_line
For a long time the coverage analysis wasn't working (because of a string of non-compatibility and using legacy tools)
Switching the code coverage analysis tool from [Coveralls](https://coveralls.io/) to [codecov](https://codecov.io/). The `codecov` interface is very clear and works out of the box with all weird things we use in the code.
There were some changes to the code generation in the case of "mark-lines" option which should make it work more robustly.
> Switching the coverage testing to codecov

- src/Handlers/cbPythonCall.cpp
- src/compare.cpp
- src/makefile.Rt
- src/makefile.main.Rt
- tools/tests.sh
The current tests rely on finding `*.xml` files and running them with a specific model. This is not extensible, and cannot cope with e.g. running solver in parallel or running test which should cause errors.
The tests are now formulated in `*.test` files. There is a `*.test` file for every test, and each of them is executed in a separate, clean directory. Needed files are copied, the solver is executed according to the description in the `*.test` file, and results are compared. 
The `*.test` files have form as follows:
```bash
need karman.xml
run $SOLVER karman.xml
csvdiff output/karman_Log_P00_00000000.csv
diff output/karman_VTK_P00_00001000.pvti
sha1 output/karman_VTK_P00_00001000.vti
```
The possible commands:
command | comment
--- | ---
`need ...` | copies files needed for a test
`run …
> Moving to a new formulation of tests

- src/makefile.main.Rt
- src/models.R
There is no way now to make a model with options, which cannot be compiled without any option selected.
The option matrix generation is based on R *formula* syntax. In this syntax one can delete the *intercept* term in the formula by adding `-1` at the end of formula. But it was not supported by our compilation mechanism uptil now.
I added the support for intercept term.
`OPT` | Models generated
--- | ---
`(A+B)*C` | `model`, `model_A`, `model_B`, `model_C`, `model_A_C`, `model_B_C`
`(A+B)*C-1` | `model_A`, `model_B`, `model_C`, `model_A_C`, `model_B_C`
`(A+B)*C-C-1` | `model_A`, `model_B`, `model_A_C`, `model_B_C`
> Fixing issue with model options

- src/makefile.main.Rt
- tools/dep.R
If you use `R` from a Singularity container, it the compilation fail on the `dep.R` script.
A Singularity conrainer cannot access parent directories. This means that if `R` is run from a Singularity container, it cannot access any files in `../` path. As `dep.R` script was called from `CLB/[model[` directory, the execution fail.
Changed the `dep.R` to get the `CLB/[model]` directory as argument.
> [hotfix] Change of dep.R call

- src/Handlers/cbFailcheck.cpp
One line bug fix to cast a CPP string (it->name) to a C string using .c_str() function.
Unstable branch now compiles and runs on Goliath cluster.
> Fixed string type error in cbFailcheck::DoIt

- src/BallTree.h
- src/Lattice.cu.Rt
- src/Particle.hpp
TCLB with particle/DEM support was giving errors when compiled with `./configure --enable-paranoid`. Two types of error are found:
Changed the index to `size_t` in the loops, and initialized particle structure with zeros when there are no particles in the RFI.
> Correcting particle support for paranoid compilation

- src/cross.hpp
The force totals on particles were wrong because of an error in reduction procedures. The error was in most cases small and only occurred in specific situations (and only on gpu).
`atomicSumWarpArr` function was using `__shfl_down` which calculated the sum only on the 0th thread. But the sum was used on all threads with `threadIdx.x < len`. This caused wrong results in some cases.
I changed the implementation of `atomicSumWarpArr` to use `__shfl_xor` (some details about the functions can be found [on nvidia](https://devblogs.nvidia.com/faster-parallel-reductions-kepler/))
> Fixing bug in atomicSumWarpArr

- src/configure.ac
Fresh pull of TCLB develop on gadi doesn't currently compile with hdf5. Adjusted line to what I had in my configure.ac that did compile and use hdf5 and is similar to the command for mpi.
> + alter line so that Gadi will compile with hdf5

- src/configure.ac
As pointed in #292 it would be useful to keep the R code which the RTemplate translates to for debugging.
A new option was introduced to `RT` (llaniewski/rtemplate#1) which stores the R code alongside the generated file. This can be activated through `./configure` script with:
```bash
./configure --enable-keepcode
make d2q9
cat CLB/d2q9/Handlers/acObjective.cpp # The generated file
cat CLB/d2q9/Handlers/acObjective.cpp.code.R # The intermediate R code
```
Additionally if `RT` generation fails, it will now always generate the intermediate R code for inspection.
Closes #292
This can be of interest to @mdzik @TravisMitchell
> Adding keepcode option to configure

- .gitmodules
- src/compare.cpp
- tools/tests.sh
In #213 I postulated that comparing results based on SHA1 sums is not a good long term strategy.
The current system makes:
- testing on different architectures impossible
- contributing new test hard
#259 introduced comparison of vti files based **on value** not checksum. This pull request removes the checksum tests entirely.
I removed the checksums for vti files, and kept just the last vti file for every test. 
This makes `TCLB_tests` repository potentially heavy in the future. We'll try to deal with it as it comes.
The `git lfs` adds a useful interface for tracking heavy files in git. The problem is that github imposes 1GB storage and 1GB/month bandwidth cap. The bandwidth especially would run out quickly combined with our continuous integration (tests on Travis-CI).
> Moving all tests to "by value" approach

- models/nonnewtonian/d3q27_kl/Dynamics.c.Rt
Of course just after I merged, I noticed an small bug in the d3q27_kl.
@bhill23, to make sure `Pin` is always initialized, I added a final `else` statement in the code. In cases of initializing values, it's generally a good idea to make such a `else` clause even if you are certain one of the conditions would be triggered. This is because uninitialized-value bugs are very hard to notice, find and debug. In many cases they will present themselves only on specific architectures.
@bhill23, could you test if everything works from your side after this change?
```bash
git clone https://github.com/llaniewski/TCLB.git TCLB_patch
cd TCLB_patch
git checkout patch/llaniewski-d3q27_kl
make configure
./configure [your options]
make -j 16 d3q27_kl
[make tests involving this part of code]
```
If …
> Correcting d3q27_kl for unitialized value

- src/Handlers.h
- src/configure.ac
- src/cross.h
- src/main.cpp
This PR fixes a bug which persisted in the code apparently for a long time in checking reference count of Handlers. This will cause Handlers to be `Finish`-ed properly and deleted. Other unwanted behaviour can be caused by this change, as until now Handlers weren't deleted until the end of the simulation.
> Fixing bug in Handler reference counting

- src/configure.ac
In some systems naming convention is troublesome, keep the option to point to the python
> Python binary option

- src/conf.R
This will not work:
```R
AddStage(XXXX)
AddField(XXXX)
```
with error
`
Error in rbind(deparse.level, ...) : 
numbers of columns of arguments do not match
`
which was not very useful. 
Not anymore
`
It seems, that you added Field after Stage in Dynamics.R - this will not parse
`
I hope it doesn't interfere with some other code ;)
> Add meaningfull error on wrong Dynamics.R file

- src/LatticeContainer.inc.cpp.Rt
It turned out that there was a long standing error in the usage of 3D block grid in `LatticeContainer`. This was affecting performance on 2D cases and high-end cards.
This PR fixes this error, but as this wasn't working earlier, and it affects the grid division into blocks, it is important to test it.
If the normal tests will pass, I'll merge it, and then we have to test it for all our applications to see if nothing broke. Things to test (only GPU is relevant):
The performance issue found by @trisbsamson
> Correcting typo in GRID3D option

- src/Handlers/cbStop.cpp.Rt
- src/Handlers/cbStop.h
This PR adds and option to stop computation when **percent** change of some global is below some level.
Usage:
```xml
<Stop FluxPercentChange="1%" Times="10" Iterations="10"/>
```
**reminder:** in TCLB `%` is a "unit" equivalent to `0.01`. So you can say `"1e-3"` or `"0.1%"`.
FYI: @TravisMitchell
> Adding PercentChange to Stop

- .travis.yml
- src/config.main.mk.in
- src/configure.ac
- src/makefile.main.Rt
- tools/install.sh
- tools/makeAD
This PR introduces an option to `tools/install.sh` to install tapenade, and adds path discovery and option to `./configure`. It also adds testing of `d2q9_adj` to CI on Travis-CI.
> Adding tapenade to install.sh and tests on travis-ci

- models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
* Fixed typo in cudadevicefunction calc_Fs(...)
After the clean up of the d3q27_pf_velocity model, the planar benchmark thermocapillary case was not tested. Moving back to this work, I tested and noticed a typo in the thermocapillary surface tension force calculation. This commit fixes and has been tested against the planar benchmark cases
> + fix typo in surf force calculation (thermocapillary)

- src/lammps.cpp
This PR improves the lammps/liggghts wrapper by allowing it to pass command line arguments to the DEM solver.
By default `-log none` will be passed to the DEM solver if no `-log` option is provided. Apart from that it is backwards compatible. The wrapper will expect the input file as the first argument, or to follow the `-in` option.
- `lammps file` -- running the `file` with `-log none` options
- `lammps file -log aa` -- running the `file` with `-log aa` options
- `lammps -log aa -in file` -- running the `file` with `-log aa` options
- `lammps -v var 3 -in file` -- running the `file` with `-v var 3 -log none` options
FYI: @ndivaira  I changed the default behaviour to disable `log` output, as it is a crush risk on clusters (and it's kind of useless, as the output is already in the …
> Passing arguments to lammps/liggghts

- src/lammps.cpp
This PR corrects the bug, which caused the lammps/liggghts wrapper to exit improperly when not coupled with TCLB.
> Correcting the exit from lammps wrapper

- src/Geometry.cpp.Rt
- src/pinned_allocator.hpp
Printing in `pinned_allocator.hpp` was quite annoying, especially when running on CPUs. 
Additionally, when testing turned out that I could not compile with verbosity level 0, due to the undefined variable in `Geometry.cpp.Rt`, so I've fixed that as well.
> Reduce logging

- src/Handlers/cbSaveCheckpoint.cpp
Fix for:
```
make: Okrężna dyrektywa CLB/d3q27_cumulant/makefile <- CLB/d3q27_cumulant/makefile porzucona.
RT         CLB/d3q27_cumulant/makefile
make[1]: Wejście do katalogu `/lu/tetyda/home/mdzik/rysy/TCLB/CLB/d3q27_cumulant'
G++        Handlers/cbSaveCheckpoint.cpp
In file included from Handlers/../CommonHandler.h:7:0,
from Handlers/cbSaveCheckpoint.h:4,
from Handlers/cbSaveCheckpoint.cpp:1:
Handlers/cbSaveCheckpoint.cpp: In member function ‘virtual int cbSaveCheckpoint::DoIt()’:
Handlers/../Global.h:196:50: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
#define debug8(...) myprint(8, 0, __VA_ARGS__) // Error
^
Handlers/../Global.h:205:24: note: in expansion of macro ‘debug8’
#define error(...) …
```
> Non trivially copyable (gcc7.3)

- src/configure.ac
Use `AS_HELP_STRING` instead of `AC_HELP_STRING`. 
`AC_HELP_STRING` is really deprecated in autoconf 2.70+ (which is one installed by macOS it seems, that is why CI was not working). `AS_HELP_STRING` is already available since autotoconf 2.60 at least (which was released in 2006, and most of systems use at least autoconf 2.69, so it safe to use). 
For similar issues see e.g: 
- https://midnight-commander.org/ticket/2560 
- https://github.com/curl/curl/issues/6647
> Fix broken CI

- src/simplepart.cpp
This PR corrects the bug, which caused the simplepart to exit improperly and making a coupled simulation hand indefinitely.
Fixes #388
> Correcting the exit from simplepart

- src/Handlers/conControl.cpp.Rt
The Param in control was not updating the "zone_number" variable after the zone name was set.
> Fixing bug in setting zone number in Control

- src/Geometry.cpp.Rt
I believe it should be plus instead of minus there, otherwise the shape is incorrect
1. Sphere ![sphere](https://user-images.githubusercontent.com/13331189/167522862-f49d4edf-2ac3-4671-b864-e7c964f7cb8c.png)
2. Half sphere without the fix (look at the top) ![half_sphere_old](https://user-images.githubusercontent.com/13331189/167522857-da9ca6c7-3103-4db1-8507-6c032192f0de.png)
3. Half sphere with the fix ![half_sphere_proper](https://user-images.githubusercontent.com/13331189/167522856-f1578963-75aa-45a9-a1cc-62be89d6923f.png)
> Fix HalfSphere geometry

- src/Handlers/cbRunR.cpp.Rt
Makes much easier generating files associated with the current iteration (e.g. I used it to generate pictures of "slices" data and saving into files with filename based on the iteration)
Not sure, where exactly it should be, I put it into `Solver$Globals` , because it made more sense than `Solver$Iteration$`, but suggestions are welcome
> Export iteration number to Rinside

- src/Sampler.cpp.Rt
During using Sampler I realised that added points are not cleared on finalising. This means next time `Sampler` is used (e.g. if used inside  two successive `Solve` handlers) previous points from the previous Sampler would still be there and would be unexpectedly present in the output.
This fixes it.
> Fix leak in Sampler

- src/Particle.hpp
- src/lammps.cpp
This PR fixes errors in compilation that happen when compiled with `--disable-double` introduced while DEM was introduced.
> Correcting float compilation

- src/configure.ac
This PR modifies configure script to correctly discover [LIGGGHTS-PFM](https://github.com/ParticulateFlow/LIGGGHTS-PFM) as DEM solver. Now both `build/` and `src/` paths are searched for the library file.
FYI: @ndivaira
> Adding support for LIGGGHTS-PFM

- src/Handlers/acGeometry.cpp
- src/Handlers/acRemoteForceInterface.cpp
- src/Lattice.cu.Rt
- src/Lattice.h.Rt
- src/LatticeContainer.h.Rt
- src/cuda.cu.Rt
- src/hdf5Lattice.cpp.Rt
- src/vtkLattice.cpp.Rt
- src/vtkOutput.cpp
- src/vtkOutput.h
Adding the option to shift the position of the lattice. It's a long overdue thing. You can set the position with `px`, `py` and `pz` arguments in the `<Geometry>` element.
The position affects:
- the `X`, `Y` and `Z` values in calculations
- the VTK export (it will be specially shifted)
- particle coupling
This does not affect:
- geometry elements like `<Box>`, `<Sphere>` or even `<STL>`. All geometry is in relation to the lattice origin.
> Adding position to lattice

- src/configure.ac
- src/hdf5Lattice.cpp.Rt
Bugs:
- quotation in "-I" option printed by Rcpp was ruining configure header test
- semicolon was missing in hdf5 after inroducing position in #414
> Fixing bugs in configure and compile

- src/LatticeAccess.inc.cpp.Rt
- src/config.h.in
- src/configure.ac
- src/types.h
This fixes a bug while compiling with RInside.
> Changing macro name to avoid name-collision with Rcpp

- src/Handlers/cbHDF5.cpp
- src/Handlers/cbHDF5.h
- src/Handlers/cbVTK.cpp
- src/Handlers/cbVTK.h
- src/Solver.cpp.Rt
- src/Solver.h.Rt
- src/cross.h
- src/hdf5Lattice.cpp.Rt
- src/hdf5Lattice.h
- src/vtkLattice.cpp.Rt
- src/vtkLattice.h
Addresses #186. Region definition works similarly to Geometry definition, negative dx and nx work backwards from domain end.
Also adds nodetypes to HDF5 outputs.
Fixes outputs for cpu only builds where the z axis was not being looped over.
> VTK and HDF5 output additions + cpu output fix

- src/Lattice.cu.Rt
When outputting small regions over multiple MPI+CUDA processes, CudeKernelRun was sometimes called with a block size of 0 raising an "invalid configuration argument" error. This change just makes Get<?%s q$name ?> return before making kernel calls and memory allocations if this is the case.
Should only impact MPI+CUDA builds, CPU-only already handled blocks with 0 size in the cross.h for loop.
> Don't exec CudaKernelRun when block/region has a size of 0

- src/Global.cpp.Rt
- src/Global.h.Rt
- src/config.h.in
- src/configure.ac
- src/main.cpp
This PR switches the `std::chrono::steady_clock::now()` for walltime measurement in output and in log `csv` files. The previous use of `::clock()` was really CPU time, and was giving misleading results.
> Switching to `steady_clock` for walltime

- .github/workflows/cpu_test.yml
- .github/workflows/gpu_comp.yml
- .github/workflows/hip_comp.yml
- .github/workflows/storage_test.yml
- src/simplepart.cpp
- tools/csvdiff
- tools/tests.sh
This PR introduces:
- tests for `d3q27_PSM` using `simplepart` for the DEM
- vibration in `simplepart`
- regexp-based exclusion in `tools/csvdiff`
> Tests for `d3q27_PSM`

- .github/workflows/cpu_test.yml
- .github/workflows/gpu_comp.yml
- .github/workflows/hip_comp.yml
- models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
- src/compare.cpp
- tools/csvdiff
- tools/etc/test.exceptions.sh
- tools/tests.sh
This PR introduces improvement in testing:
- periodic offset option in `compare` which allows to compare two `vti/pvti` files with a spatial offset.
- adding a file (`tools/etc/test.exceptions.sh`) with test exceptions
- test for `d3q27_pf_velocity` (drop on wall)
> Improved tests

- src/Lattice.cu.Rt
- src/LatticeContainer.h.Rt
- src/LatticeContainer.inc.cpp.Rt
- src/conf.R
- src/config.R.in
- src/configure.ac
- src/cross.h
This PR improved the OpenMP support and introduces `--cpu-layout` option for better performance on CPUs.
> Improved OpenMP support

- models/electrokinetic/d2q9_poison_boltzmann/Dynamics.R
- models/experimental/d3q27_csf/Dynamics.R
- models/flow/auto/Dynamics.R
- models/flow/d2q9_par/Dynamics.R
- models/flow/d3q27_cumulant_part/Dynamics.R
- models/heat/d3q27_tePSM_per/Dynamics.R
- models/multiphase/d2q9_ShanChen/Dynamics.R
- models/multiphase/d2q9_csf/Dynamics.R
- models/multiphase/d2q9_kuper/Dynamics.R
- models/multiphase/d2q9_pf/Dynamics.R
- models/multiphase/d2q9_pf_pressureEvolution/Dynamics.R
- models/multiphase/d2q9_pf_velocity/Dynamics.R
- models/multiphase/d2q9_scmp/Dynamics.R
- models/multiphase/d3q19_kuper/Dynamics.R
- models/multiphase/d3q27_pf_velocity/Dynamics.R
- models/multiphase/experimental/d2q9_pp_LBL/Dynamics.R
- models/multiphase/experimental/d2q9_pp_MCMP/Dynamics.R
- models/reaction/d2q9_reaction_diffusion_system/Dynamics.R
- src/LatticeAccess.inc.cpp.Rt
- src/SUMMARY.Rt
- src/conf.R
- src/cuda.cu.Rt
This PR introduces a new mechanism for setting and testing the access policy for fields in stages.
The `AddStage` has now three arguments:
- `load.densities=` specifies the `Densities` that are loaded at the beginning of the stage.
- `read.fields=` specifies the `Fields` that can be accessed in the Dynamics with `field(dx,dy,dz)` macros.
- `save.fields=` specifies the `Fields` that are saved at the end of the stage.
By default the actions/stages setup is:
```R
AddStage(main="Run", name="BaseIteration", load.densities=TRUE, read.fields=TRUE, save.fields=TRUE)
AddStage(main="Init", name="BaseInit", load.densities=FALSE, read.fields=FALSE, save.fields=TRUE)
AddAction(name="Iteration", stages=c("BaseIteration"))
AddAction(name="Init", stages=c("BaseInit"))
```
Moreover, the default …
> Field access checks

- models/multiphase/d3q27_pf_velocity/Dynamics.R
- models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
Currently the density pnorm is part of the Vel group which is saved after the first stage of init, although its value isn't calculated until a later stage. 
To stop the testing error for now, pnorm is initially set to zero in this first stage. Future considerations around moving this and U,V,W to fields rather than densities are highlighted to provide distinction between streamed densities required by the model and fields that are determined from these.
> Fixing error in test from d3q27_pf_velocity

- src/conf.R
- tools/format.sh
This adds automatic formatting of R files with
```bash
tools/format.sh file.R
```
> Adding formatting of R code to tools/format.sh

- models/multiphase/d2q9_pf_velocity/Dynamics.R
- models/multiphase/d2q9_pf_velocity/Dynamics.c.Rt
- models/multiphase/d2q9_pf_velocity/conf.mk
this initial fix at least allows the d2q9 phase field model to be run with normal cases. There is a chance that very complex geometry may cause edge conditions (e.g. where a solid node has a normal direction that points to another solid) that may require the introduction of a new field in the future. 
Note that use of nan makes failcheck require to be applied with a focus area.
> Arb fix/d2q9 pf velocity

- models/multiphase/d3q27_pf_velocity/Dynamics.R
- models/multiphase/d3q27_pf_velocity/Dynamics.c.Rt
This fixes the problem of uninitialised values in the `InitFromFieldsStage` stage.
@shkodm Could you make it a priority to test if this doesn't break your computations?
> Corrections for uninitialised fields in d3q27_pf_velocity

- .gitignore
- tools/csvconcatenate
- tools/tests.sh
This adds tests for the restarting mechanics for `d2q9`. Tests both `vtk` files as well as `csv`.
Also adds a simple tool for merging `csv` files from restart runs.
> Adding tests for the restart mechanics

- src/main.cpp
> Adding exception for adding setting zones

- src/xpath_modification.cpp
This simplifies the interface for the most common, global options:
```bash
CLB/d2q9/main example/flow/2d/karman.xml . @toArb = "y" . @remove_bulk = "Wall"
```
becomes now:
```bash
CLB/d2q9/main example/flow/2d/karman.xml --toArb true --remove_bulk Wall
```
> Adding double-dash options

- src/makefile.main.Rt
- src/models.R
- tools/dep.R
Supersedes #493
- `-E` in sed to be POSIX compliant
- Remove regex in `find` to make it more tolerable and portable
- `find models/` produces extra slashes in results on macos ( i.e. `models//multiphase/`) but not on Linux. `find models` does not give extra slashes and behaves the same as `find models/` on models
Tested on my M2 Macbook Air, all the clusters where I use TCLB, and my workstation. 
@TravisMitchell  FYI 
I will also CI at some point, but not in this PR.
> Add fixes for building on macOS

- src/CartLattice.cpp.Rt
- src/cross.cu
If one want to calculate (potentially) huge product of int-s, you should do:
```c++
int nx,ny,nz;
size_t n = (size_t) nx*ny*nz;
```
which is equivalent to:
```c++
size_t n = ((((size_t) nx)*ny)*nz);
```
which is different than:
```c++
size_t n = (size_t) (nx*ny*nz);
```
which first multiplied (overflows) and then converts.
Fixes #496
> Correcting the size calculation in allocation of CartLattice's FTabs

- src/CartLatticeAccess.hpp.Rt
Fixes #492 
TODO after:
1. make some tests for `autosym`
2. make `SymmetryAccess` work with arbitrary lattice
> Fixing NodeType expressions in SymmetryAccess

- src/Geometry.cpp.Rt
The main loop for the sweep was unnecessarily repeating the spline calculation, and also looping over regions unnecessarily large. 
A very simple 'adaptive' step is also added, and the distance calculation brought into line with the other geometry types (pipes/spheres/etc) with the 0.5 offset, so the sweep can be combined smoothly with the other types.
> Improve the Sweep geometry

- src/Handlers/acSolve.cpp
- src/Handlers/cbRunR.cpp
- src/Handlers/cbRunR.h
Adding `ITER_LASTGLOB` to RunR element, and to the last iteration of Solve action.
@shkodm, could you test this?
> Fixing the globals in RunR

- src/LatticeAccess.inc.cpp.Rt
- src/conf.R
- src/makefile.main.Rt
- src/models.R
This PR introduces and alternative version of the `autosym` capability. All models with the `autosym` option can now be compiled with `autosym2` option, which introduces `SymmetryEdge` boundary conditions, which are symmetry boundary conditions, but not on the middle of element, but on the edge of the element. This allows for using symmetry in common cases with even number of elements. Eg. for a simulation of a droplet, with `autosym` we need 99x99 cross-section, and the center of the droplet at 49.5, with the reduced domain to 50x50 with symmetry, and with `autosym2` one can use a channel of 100x100 and the particle can be centrally between elements at 50.
> Introducing `autosym2`
